"""equipo activo

Revision ID: 025774a4a9a6
Revises: 1af1bfda6cc1
Create Date: 2024-08-02 09:51:33.399003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025774a4a9a6'
down_revision = '1af1bfda6cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
