"""vode nuevo activo

Revision ID: 1376886f87d4
Revises: bcba92c9a561
Create Date: 2024-07-31 15:17:30.166845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1376886f87d4"
down_revision = "bcba92c9a561"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("marca", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activo", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("marca", schema=None) as batch_op:
        batch_op.drop_column("activo")

    # ### end Alembic commands ###
