"""crear equipo

Revision ID: 1af1bfda6cc1
Revises: 1dc4290a1f77
Create Date: 2024-08-01 02:11:19.483104

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1af1bfda6cc1"
down_revision = "1dc4290a1f77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("marca_id", sa.Integer(), nullable=False),
        sa.Column("modelo_id", sa.Integer(), nullable=False),
        sa.Column("caracteristica_id", sa.Integer(), nullable=False),
        sa.Column("accesorio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accesorio_id"],
            ["accesorio.id"],
        ),
        sa.ForeignKeyConstraint(
            ["caracteristica_id"],
            ["caracteristica.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categoria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marca_id"],
            ["marca.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modelo_id"],
            ["modelo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipo")
    # ### end Alembic commands ###
