"""crear activo accesorios

Revision ID: 1dc4290a1f77
Revises: f4c4dfe4048f
Create Date: 2024-08-01 01:00:29.208398

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1dc4290a1f77"
down_revision = "f4c4dfe4048f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accesorio", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activo", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accesorio", schema=None) as batch_op:
        batch_op.drop_column("activo")

    # ### end Alembic commands ###
