"""creacion de caracteristicas

Revision ID: 20fb8f6110ee
Revises: fa3a27a29c4a
Create Date: 2024-07-31 19:57:44.398683

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20fb8f6110ee"
down_revision = "fa3a27a29c4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caracteristica",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("peso", sa.Float(), nullable=True),
        sa.Column("resolucion_pantalla", sa.String(length=100), nullable=True),
        sa.Column("capacidad_bateria", sa.Integer(), nullable=True),
        sa.Column("sistema_operativo", sa.String(length=50), nullable=True),
        sa.Column("precio_lista", sa.Float(), nullable=True),
        sa.Column("camara", sa.String(length=200), nullable=True),
        sa.Column("descripcion", sa.String(length=200), nullable=False),
        sa.Column("lanzamiento", sa.Date(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("caracteristica")
    # ### end Alembic commands ###
