"""fecha en inventario

Revision ID: 400a37f88272
Revises: d143cdafa246
Create Date: 2024-08-02 10:29:29.738930

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "400a37f88272"
down_revision = "d143cdafa246"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fecha", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.drop_column("fecha")

    # ### end Alembic commands ###
