"""largo de nuevo

Revision ID: 66863106dda5
Revises: 7edee4d1f52d
Create Date: 2024-08-01 00:06:14.090357

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "66863106dda5"
down_revision = "7edee4d1f52d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("caracteristica", schema=None) as batch_op:
        batch_op.alter_column(
            "camara",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=200),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "descripcion",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("caracteristica", schema=None) as batch_op:
        batch_op.alter_column(
            "descripcion",
            existing_type=sa.String(length=200),
            type_=mysql.VARCHAR(length=50),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "camara",
            existing_type=sa.String(length=200),
            type_=mysql.VARCHAR(length=50),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
