"""fecha en cliente

Revision ID: 6e14959af540
Revises: f56fb8178107
Create Date: 2024-08-02 11:37:00.966852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e14959af540"
down_revision = "f56fb8178107"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cliente", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fecha", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cliente", schema=None) as batch_op:
        batch_op.drop_column("fecha")

    # ### end Alembic commands ###
