"""relacion modelo caracteristica

Revision ID: 7edee4d1f52d
Revises: 58e6473bfb85
Create Date: 2024-07-31 23:59:30.114301

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7edee4d1f52d"
down_revision = "58e6473bfb85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("caracteristica", schema=None) as batch_op:
        batch_op.add_column(sa.Column("modelo_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "modelo", ["modelo_id"], ["id"])
        batch_op.drop_column("nombre")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("caracteristica", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nombre", mysql.VARCHAR(length=50), nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("modelo_id")

    # ### end Alembic commands ###
