"""mofabricante activo

Revision ID: a50a7ec49313
Revises: a78824c814b8
Create Date: 2024-07-31 17:03:43.076644

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a50a7ec49313"
down_revision = "a78824c814b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fabricante", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activo", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fabricante", schema=None) as batch_op:
        batch_op.drop_column("activo")

    # ### end Alembic commands ###
