"""hash

Revision ID: a88b0ef51efd
Revises: f2a98a01df56
Create Date: 2024-09-03 21:07:21.914760

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a88b0ef51efd"
down_revision = "f2a98a01df56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=50), nullable=False)
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", mysql.VARCHAR(length=50), nullable=False)
        )
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
