"""volver

Revision ID: bcba92c9a561
Revises: f65221b1e9e1
Create Date: 2024-07-31 15:10:35.379736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcba92c9a561'
down_revision = 'f65221b1e9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
