"""modificar inventario

Revision ID: d143cdafa246
Revises: c790da43a6f5
Create Date: 2024-08-02 10:25:35.173716

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d143cdafa246"
down_revision = "c790da43a6f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nombre", sa.String(length=50), nullable=False))
        batch_op.drop_constraint("inventario_ibfk_1", type_="foreignkey")
        batch_op.drop_column("modelo_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventario", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "modelo_id",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            "inventario_ibfk_1", "modelo", ["modelo_id"], ["id"]
        )
        batch_op.drop_column("nombre")

    # ### end Alembic commands ###
