"""quiero irme

Revision ID: f0f4ff57a30f
Revises: a88b0ef51efd
Create Date: 2024-09-03 21:16:11.932105

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f0f4ff57a30f"
down_revision = "a88b0ef51efd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=300),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=300),
            type_=mysql.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
