"""crear accesorios

Revision ID: f4c4dfe4048f
Revises: 66863106dda5
Create Date: 2024-08-01 00:49:08.743986

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4c4dfe4048f"
down_revision = "66863106dda5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesorio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modelo_id", sa.Integer(), nullable=False),
        sa.Column("cargador", sa.Boolean(), nullable=True),
        sa.Column("auriculares", sa.Boolean(), nullable=True),
        sa.Column("chip", sa.Boolean(), nullable=True),
        sa.Column("funda", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modelo_id"],
            ["modelo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accesorio")
    # ### end Alembic commands ###
