"""creacion de cliente7

Revision ID: f56fb8178107
Revises: 18be33539b8b
Create Date: 2024-08-02 11:32:50.893115

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f56fb8178107"
down_revision = "18be33539b8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("dni", sa.String(length=20), nullable=False),
        sa.Column("inventario_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventario_id"],
            ["inventario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dni"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cliente")
    # ### end Alembic commands ###
